### ISSUE TITLE
If I upgrade from 3.8.0 to anything else, the page breaks.

### ISSUE THREAD

**Issue by the-real-graybags** [hilverd/glossary-page-template#11]
Hi,

I've not visited here for a while, but I thought I'd see if there has been any developments, and there really has!

My glossary is using 3.8.0, and if I change it too anything more recent than that, I just get a page saying "Glossary Page Template
This page includes a web interface..."  

Clearly I've done something wrong, but what is it?!  Thanks.

Gray

**Comment by hilverd** [comment]
I haven't been able to reproduce this yet, unfortunately -- are you hosting the static assets yourself or pointing to glstatic.net? Can you maybe share the glossary file and/or the steps you were following to upgrade in more detail please?

**Comment by the-real-graybags** [comment]
I'm pointing to glstatic.net.  Works with 3.8.0 but not with 5.

It's obviously something I've done wrong my end :( , so I've editted and attached my file.

[glossary2.zip](https://github.com/user-attachments/files/16963149/glossary2.zip)

**Comment by hilverd** [comment]
Thanks for reporting this and helping me reproduce this. You weren't doing anything wrong -- I had changed the behaviour without documenting this properly :grimacing:.

From version 4.0.0 onwards, opening the `glossary.html` file directly in a browser (as a `file://` URL) only shows the help message, not the actual glossary. So opening it as a file in the browser now just meant as a starting point. To see the glossary contents, you will need to either use the `node` command in the help message that runs the built-in editor, or "host" the file using e.g.

```
python3 -m http.server 8000
```

For what it's worth, I was forced to make this change so that I could start using query parameters (to keep track of the tag currently being filtered by, and the current sort order), and I couldn't see any good alternatives. It's unfortunate that this adds more friction.

(I've belatedly documented this change in the `CHANGELOG` and the release notes for version 4.0.0.)

**Comment by the-real-graybags** [comment]
Thanks for the reply. So, am I stuck with using 3.8.0 for my glossary? It's no big deal, it's still works perfectly for my needs. On another note, is there a way I can use the dark theme by default? At the moment it defaults to the light theme. Thanks again for creating this, it's great. Graeme Sent from my Galaxy
-------- Original message --------From: Hilverd Reker ***@***.***> Date: 15/09/2024  6:27 pm  (GMT+00:00) To: hilverd/glossary-page-template ***@***.***> Cc: the-real-graybags ***@***.***>, Author ***@***.***> Subject: Re: [hilverd/glossary-page-template] If I upgrade from 3.8.0 to anything else, the page breaks. (Issue #11) 
Thanks for reporting this and helping me reproduce this. You weren't doing anything wrong -- I had changed the behaviour without documenting this properly 😬.
From version 4.0.0 onwards, opening the glossary.html file directly in a browser (as a "notranslate">node command in the help message that runs the built-in editor, or "host" the file using e.g.
python3 -m http.server 8000

For what it's worth, I was forced to make this change so that I could start using query parameters (to keep track of the tag currently being filtered by, and the current sort order), and I couldn't see any good alternatives. It's unfortunate that this adds more friction.
(I've belatedly documented this change in the CHANGELOG and the release notes for version 4.0.0.)

**Comment by hilverd** [comment]
Sorry for the delay -- yes opening a glossary file via a `file://` URL no longer works properly after 3.8.0. But I think I have found a way to fix that. I will also add an option under "Settings" to allow changing the default theme.

I will post an update here once I have managed to release those changes.

**Comment by hilverd** [comment]
This should now be fixed in [v5.1.0](https://github.com/hilverd/glossary-page-template/releases/tag/v5.1.0) which also adds the ability to change the default theme.

If you want to try it then hopefully upgrading shouldn't be too painful, although there were breaking changes in [v4.0.0](https://github.com/hilverd/glossary-page-template/releases/tag/v4.0.0) and [v5.0.1](https://github.com/hilverd/glossary-page-template/releases/tag/v5.0.1).

I'll close this issue now but can reopen it if something isn't OK.
