### ISSUE TITLE
adding tags to definition and filtering by tags

### ISSUE THREAD

**Issue by iacopoff** [hilverd/glossary-page-template#8]
Great project! I was thinking about the possibility to add tags to definitions and then filtering by selected tags. The tags would be like categories and would provide ways to separate contexts. Looking forward to hear your thoughts on that

**Comment by hilverd** [comment]
Thanks! I like that idea -- I've been thinking about it before but other things seemed higher priority. I need to do another patch release first and then I will revisit the tags idea and post some thoughts here.

**Comment by hilverd** [comment]
I have given this some thought and I'm not sure if it's a good idea to add functionality for tags at this time. Filtering in particular seems tricky, I think it may cause more problems than it's worth. I've written up my reasoning below. It's a bit long, but if you make it to the end and you think I'm being too negative then of course I'd be interested in your opinion.

## How tags/topics might work

Instead of "tags" the term "topics" (which e.g. GitHub uses) seems a bit nicer. Here's how I think functionality for topics would work.

* Each definition can be labelled by zero or more topics. Given that an item can have multiple definitions for its term(s), that means topics could be used to provide different definitions for different "contexts".

* You can filter by topics -- let's say only one topic X at a time. Presumably this would mean that you see only items that "match" X. An item matches X if one of its definitions is labelled by X. And maybe an item should also be considered to match X if it contains no definitions but it links to a related term whose item matches X.

* When filtering by a topic X, what if there's an item that has multiple definitions but only some are labelled by X? Should only the X-labelled definitions for that item be shown? I'm not completely convinced that would be the right thing to do. (For related terms it does seem clear that you would only show the ones whose item matches X.)

It seems to me that topics would mainly be useful for big glossaries, and the main benefit would be that you can quickly see what topic(s) a definition/term/item is about. But in practice I think there will be a lot of items where the question "is this item relevant to topic X?" is not that easy to answer. Managing topics might not be easy. Some items might clearly fall under a certain topic and others might only be vaguely related to X -- how should they be labelled? And even if a glossary does contain only definitions for clearly separate topics, then wouldn't it make more sense to create separate glossaries?

I don't remember seeing any glossaries "in the wild" where tags/topics were being used, and I think this might be because of the reasons above.

## Possible alternative -- order items by focus on a specific item

For larger glossaries it does seem like it would be nice to be able to read through those items that are most relevant to a specific topic. The topics that you might want to do this for are probably actually represented by items themselves. So I was thinking that it might be useful to be able to order a glossary's items in a way that is "focused" on a certain item X. The item X itself would be shown first. Then any items that are immediately connected to X via "See also" links. After that, any items that are two steps away from X via "See also" links, etc. Items that don't have any "See also" path to/from X at all would be listed separately as they seem unrelated.

I haven't tried this out yet but it seems like an interesting lightweight alternative to allow browsing items focused on a specific "topic" within larger glossaries.

**Comment by hilverd** [comment]
For what it's worth, version 3.6.0 now supports ordering items "focused" on a particular topic/item. It seems to work reasonably well but there is probably room for improvement.

I think this issue should stay open as I'd like to revisit the tags/topics filtering idea at some point soon.

**Comment by iacopoff** [comment]
Thanks for your thoughts and for implementing the topics feature, it seems great!

I try to explain why I am considering "topics" (I agree topics is better than tags for what we are trying to achieve here) to separate contexts in a glossary.

I am working on a glossary for a knowledge system to collect, validate, store, query requirements for Earth Observation products and services. The overarching context is therefore EO, but as you can imagine there are many EO applications (biodiversity, emergency management, etc) each representing a context that intersects with EO. The "issue" is that there may be terms that are used with different meaning, and therefore that have different definitions, depending on the EO application context. For example `timeliness` is polysemantic in this EO system glossary. 

> When filtering by a topic X, what if there's an item that has multiple definitions but only some are labelled by X 

In my opinion I would like an item to be atomic, only one definition, not many. Therefore the item is unique, in database jargon it is described by a primary key composed by item and context. Maybe the item could be described by a "composed/complex" definition, by the different ways of looking at the item but always within a context.

**Comment by hilverd** [comment]
Many thanks for taking the time to explain your use case, which sounds interesting. I can see how tags or "topics" would be useful/necessary.

I've been thinking about what would need to change in the UI and data model. So far I've been trying to be "compatible" with the way HTML represents the [`<dl>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl), where each "item" can contain one or more terms together with one or more definitions. But that doesn't seem like a good fit any more, and it also seems different from the way things are done in more sophisticated formats such as [SKOS](https://www.w3.org/TR/skos-primer/).

I'm going to try and move to one definition per item as you suggest, and then add support for tags/topics. I'm still trying to figure out the details (and how to stay backwards compatible).

**Comment by hilverd** [comment]
I've just [released version 4.0.0](https://github.com/hilverd/glossary-page-template/releases/tag/v4.0.0) which adds supports for tags.

A special use case for tags is if two items have the same ("preferred") term, because you can then select so called "disambiguation tags" for both.

For example, if you have a glossary that contains an item for the term "Default" with its meaning described as it is in computer science, but also an item for the term "Default" with its meaning described as it is in finance, then you can use the tags "Computer Science" and "Finance" respectively to disambiguate them. You can see this example if you download [glossary.html](https://github.com/hilverd/glossary-page-template/releases/latest/download/glossary.html) for the new release.

I'll be trying to apply this for the larger glossary that I'm maintaining for my employer. I'm hoping that it fits your use case as well, if you're still interested.

**Comment by hilverd** [comment]
I'm closing this issue now, but feel free to ask me to reopen it to continue the discussion.
